### ISSUE TITLE
Multiple occurrences of a symbol are not correctly highlighted

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#173] opened 2020-09-13 06:52 UTC
**Describe the bug**
If I click on a word/symbol, all occurrences of that symbol should be highlighted. This no longer happens, *unless* I click on the symbol name inside of a usage message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Type a symbol name multiple times
2. Create a usage message for the symbol
3. Move the cursor onto a symbol name either inside or outside the usage message, and observe which occurrences of the symbol get highlighted

**Screenshots**

![screencap](https://user-images.githubusercontent.com/1212871/93012119-d1fe5c80-f59d-11ea-9299-79da946fe4b3.gif)

**Please also provide:**

_Plugin version:_ 2020.2

_IDEA version:_

IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 24, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.show.fileType.icon.in.titleBar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.github.gilday.darkmode, de.halirutan.mathematica, pro.bashsupport, Pythonid

**Comment by halirutan** [comment] 2020-09-13 10:55
Thanks a lot for the report. I could reproduce the issue. Resolving symbols, which is done here, has always required a lot of workarounds because IntelliJ didn't like that WL can have `$` in their symbol names. It seems the issue you found affects the "instant symbol resolution" used to highlight occurrences. Renaming still seems to work.

I need to dig deeper into the underlying cause.

**Comment by szhorvat** [comment] 2020-09-18 08:25
There's this weird thing where I see not one, but two entries for the same symbol in "Find Usages":

<img width="266" alt="image" src="https://user-images.githubusercontent.com/1212871/93574854-399b1a00-f999-11ea-9bbc-25ae4806b476.png">

One of them finds no usages, the other one finds what I expect.

I'll make a minimal example with a more complete description later. For now, I just wanted to mention it.

**Comment by halirutan** [comment] 2020-10-12 02:23
@szhorvat Just a quick update. I got a grip on this last weekend and I hope to push an EAP soon where we can test things carefully and tie up loose ends.

**Comment by szhorvat** [comment] 2020-10-13 11:30
Let me know when you pushed it in case I don't get the update automatically!

**Comment by halirutan** [comment] 2020-11-27 01:38
@szhorvat Can you try something for me, just to be sure? Go to **Help | Find Action** and search for "Registry". In the window that pops up, search for `ide.symbol.identifier.highlighting` and uncheck it. If that works, then I found the culprit and I need to assess the best way forward. In short, the identifier highlighting pass changed drastically which is why renaming and searching are not affected.

**Comment by szhorvat** [comment] 2020-11-27 09:27
Yes, that works. Any bad effects from leaving it off?  This problem has really been bothering me and I was just thinking about pinging this issue yesterday.

**Comment by halirutan** [comment] 2020-11-27 10:44
No, there shouldn't be any. The commit that introduced the issue is [this one](https://github.com/JetBrains/intellij-community/commit/624c6851391537af8a1c7659c1ee0c6af4709b48#diff-6cd1dbc4807c63402830c5ee714cdbd11616fc76b4eae0e921da249aab3e1759R89-R95) and more specifically, you find these lines

```
if (Registry.is("ide.symbol.identifier.highlighting")) {
      highlightReferencesAndDeclarations();
}
else {
      highlightReferencesAndDeclarationsOld();
}
```

So for some reason, the new default highlighting breaks it for WL and until now, we got this for free. I need to check if it can be repaired or if it isn't better to implement a `HighlightUsagesHandler` for WL.

**Comment by halirutan** [comment] 2020-12-02 03:59
@szhorvat Please check out [the new beta](https://plugins.jetbrains.com/plugin/7232-wolfram-language/versions/beta/104315) which works for 2020.3 products. Don't forget to turn the registry key you changed back to the default.

**Comment by szhorvat** [comment] 2020-12-02 16:20
I'm running it, and after a quick check it looks to be working (I restored the registry key), but I might not have a lot of time to actually use it this work.

Thanks so much for fixing this! It was a tough nut.

**Closed as completed** 2021-04-11 02:58 UTC
Labels: bug
