### ISSUE TITLE
Syntax Highlighting with unused variables in scoping constructs

### ISSUE THREAD

**Issue by eduardoofthehour** [halirutan/Mathematica-IntelliJ-Plugin#86] opened 2017-09-15 17:14 UTC
I would like to be able to see when I have unused local variables defined in a scoping construct

**Comment by kubaPod** [comment] 2017-09-15 17:52
Duplicate of #55

**Comment by eduardoofthehour** [comment] 2017-09-15 17:57
my bad

**Closed as completed** 2017-09-18 03:15 UTC
