### ISSUE TITLE
Misidentified syntax error with RepeatedPattern

### ISSUE THREAD

**Issue by MrHirenP** [halirutan/Mathematica-IntelliJ-Plugin#105] opened 2018-06-27 01:38 UTC
RepeatedPattern symbol `..` following an integer causes parser to think there is a syntax error.  This is probably due to confusing first dot as marking an inexact number.

*Mathematica* plugin

![screen shot 2018-06-26 at 9 37 22 pm](https://user-images.githubusercontent.com/26680488/41948089-23249e1e-7989-11e8-856f-3e194b70a429.png)

*Mathematica* front end (`.wl` package editor):

![screen shot 2018-06-26 at 9 36 33 pm](https://user-images.githubusercontent.com/26680488/41948065-08c4fa64-7989-11e8-8496-888a5e65b498.png)

**Comment by halirutan** [comment] 2018-06-27 14:09
Duplicate of https://github.com/halirutan/Mathematica-IntelliJ-Plugin/issues/31

**Closed as completed by halirutan** 2018-06-27 14:09 UTC
